TRUNCATE TABLE movies CASCADE;
TRUNCATE TABLE genres CASCADE;
TRUNCATE TABLE movie_genre CASCADE;
TRUNCATE TABLE score CASCADE;
TRUNCATE TABLE persons CASCADE;
TRUNCATE TABLE professions CASCADE;
TRUNCATE TABLE character CASCADE;
TRUNCATE TABLE casts CASCADE;